#!/usr/bin/env python3
"""
merge_traffic.py — 合并 traffic/raw/ 下所有原始 JSON，生成 data.js（支持多仓库）

配置文件: traffic/config.json
运行: python3 scripts/merge_traffic.py
"""
import json
import re
import sys
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).parent.parent
TRAFFIC_DIR = ROOT / "traffic"
RAW_DIR = TRAFFIC_DIR / "raw"
DATA_JS = TRAFFIC_DIR / "data.js"
CONFIG = TRAFFIC_DIR / "config.json"


def load_config() -> list[str]:
    if CONFIG.exists():
        return json.loads(CONFIG.read_text(encoding="utf-8")).get("repos", [])
    return ["breath57/dingtalk-skills"]


def load_existing() -> dict:
    if not DATA_JS.exists():
        return {"repos": {}}
    m = re.search(
        r"const TRAFFIC_DATA\s*=\s*(\{.*\})\s*;",
        DATA_JS.read_text(encoding="utf-8"),
        re.DOTALL,
    )
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    return {"repos": {}}


def merge_repo(repo: str, existing_repo: dict) -> dict:
    slug = repo.replace("/", "_")
    repo_raw = RAW_DIR / slug
    daily: dict = existing_repo.get("daily", {})

    for f in sorted(repo_raw.glob("clones-*.json")):
        try:
            for entry in json.loads(f.read_text()).get("clones", []):
                day = entry["timestamp"][:10]
                daily.setdefault(day, {})
                daily[day]["clones"] = entry["count"]
                daily[day]["clone_uniques"] = entry["uniques"]
        except Exception as e:
            print(f"⚠  跳过 {f.name}: {e}", file=sys.stderr)

    for f in sorted(repo_raw.glob("views-*.json")):
        try:
            for entry in json.loads(f.read_text()).get("views", []):
                day = entry["timestamp"][:10]
                daily.setdefault(day, {})
                daily[day]["views"] = entry["count"]
                daily[day]["view_uniques"] = entry["uniques"]
        except Exception as e:
            print(f"⚠  跳过 {f.name}: {e}", file=sys.stderr)

    summary = existing_repo.get("summary", {})
    repo_files = sorted(repo_raw.glob("repo-*.json"))
    if repo_files:
        try:
            r = json.loads(repo_files[-1].read_text())
            summary["stars"] = r.get("stars", 0)
            summary["forks"] = r.get("forks", 0)
        except Exception:
            pass

    summary["total_clones"] = sum(d.get("clones", 0) for d in daily.values())
    summary["total_clone_uniques"] = sum(d.get("clone_uniques", 0) for d in daily.values())
    summary["total_views"] = sum(d.get("views", 0) for d in daily.values())
    summary["total_view_uniques"] = sum(d.get("view_uniques", 0) for d in daily.values())

    return {
        "name": repo,
        "summary": summary,
        "daily": dict(sorted(daily.items())),
    }


def main():
    repos = load_config()
    existing = load_existing()
    existing_repos = existing.get("repos", {})

    all_repos = {}
    for repo in repos:
        slug = repo.replace("/", "_")
        (RAW_DIR / slug).mkdir(parents=True, exist_ok=True)
        all_repos[slug] = merge_repo(repo, existing_repos.get(slug, {}))

    result = {
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "repos": all_repos,
    }

    js = (
        "// Auto-generated by scripts/merge_traffic.py — do not edit manually\n"
        "const TRAFFIC_DATA = "
        + json.dumps(result, indent=2, ensure_ascii=False)
        + ";\n"
    )
    DATA_JS.write_text(js, encoding="utf-8")

    for slug, rd in all_repos.items():
        s = rd["summary"]
        days = len(rd["daily"])
        print(
            f"  {rd['name']}: {days} 天, "
            f"clone={s['total_clones']}, view={s['total_views']}, "
            f"⭐{s.get('stars', 0)}"
        )
    print(f"✅ data.js 已更新 ({len(all_repos)} 个仓库)")


if __name__ == "__main__":
    main()
