#!/usr/bin/env python3
"""
merge_traffic.py — 合并 docs/traffic/raw/ 下所有原始 JSON 文件，生成 data.js

运行: python3 scripts/merge_traffic.py
"""
import json
import re
import sys
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).parent.parent
TRAFFIC_DIR = ROOT / "traffic"
RAW_DIR = TRAFFIC_DIR / "raw"
DATA_JS = TRAFFIC_DIR / "data.js"


def load_existing() -> dict:
    """加载已有的 data.js 中的数据（增量合并用）"""
    if not DATA_JS.exists():
        return {"repo": "breath57/dingtalk-skills", "daily": {}, "summary": {}}
    m = re.search(
        r"const TRAFFIC_DATA\s*=\s*(\{.*\})\s*;",
        DATA_JS.read_text(encoding="utf-8"),
        re.DOTALL,
    )
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    return {"repo": "breath57/dingtalk-skills", "daily": {}, "summary": {}}


def main():
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    data = load_existing()
    daily: dict = data.get("daily", {})

    # 合并 clone 文件
    clone_files = sorted(RAW_DIR.glob("clones-*.json"))
    for f in clone_files:
        try:
            for entry in json.loads(f.read_text()).get("clones", []):
                day = entry["timestamp"][:10]
                daily.setdefault(day, {})
                daily[day]["clones"] = entry["count"]
                daily[day]["clone_uniques"] = entry["uniques"]
        except Exception as e:
            print(f"⚠  跳过 {f.name}: {e}", file=sys.stderr)

    # 合并 view 文件
    view_files = sorted(RAW_DIR.glob("views-*.json"))
    for f in view_files:
        try:
            for entry in json.loads(f.read_text()).get("views", []):
                day = entry["timestamp"][:10]
                daily.setdefault(day, {})
                daily[day]["views"] = entry["count"]
                daily[day]["view_uniques"] = entry["uniques"]
        except Exception as e:
            print(f"⚠  跳过 {f.name}: {e}", file=sys.stderr)

    # 取最新 repo stats
    summary = data.get("summary", {})
    repo_files = sorted(RAW_DIR.glob("repo-*.json"))
    if repo_files:
        try:
            repo = json.loads(repo_files[-1].read_text())
            summary["stars"] = repo.get("stars", summary.get("stars", 0))
            summary["forks"] = repo.get("forks", summary.get("forks", 0))
        except Exception:
            pass

    # 计算累计总量（各日求和，注意 GitHub 每日独立计数，汇总会略高于实际唯一数）
    summary["total_clones"] = sum(d.get("clones", 0) for d in daily.values())
    summary["total_clone_uniques"] = sum(d.get("clone_uniques", 0) for d in daily.values())
    summary["total_views"] = sum(d.get("views", 0) for d in daily.values())
    summary["total_view_uniques"] = sum(d.get("view_uniques", 0) for d in daily.values())

    result = {
        "repo": "breath57/dingtalk-skills",
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "summary": summary,
        "daily": dict(sorted(daily.items())),
    }

    js = (
        "// Auto-generated by scripts/merge_traffic.py — do not edit manually\n"
        "const TRAFFIC_DATA = "
        + json.dumps(result, indent=2, ensure_ascii=False)
        + ";\n"
    )
    DATA_JS.write_text(js, encoding="utf-8")
    days = len(daily)
    print(
        f"✅ data.js 已更新：{days} 天数据，"
        f"累计 clone={summary['total_clones']}，"
        f"view={summary['total_views']}，"
        f"⭐{summary.get('stars', 0)}"
    )


if __name__ == "__main__":
    main()
